
server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///home/mhlee/Documents/local-repo
  rabiitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest